<wsdl:definitions
     name="CallKC1"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/Development/SchemaSearchAndReplace/CallKC1"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/Development/SchemaSearchAndReplace/CallKC1"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/CallKC1"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
  <plt:partnerLinkType name="CallKC1_plt" >
    <plt:role name="CallKC1_role" >
      <plt:portType name="tns:CallKC1_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/CallKC1" schemaLocation="../Schemas/CallKC1_table.xsd" />
      </schema>
    </wsdl:types>
    <wsdl:message name="CallKC1Select_inputParameters">
        <wsdl:part name="CallKC1Select_inputParameters" element="top:CallKC1Select_p_ORDInputParameters"/>
    </wsdl:message>
    <wsdl:message name="Otmsoal2Collection_msg">
        <wsdl:part name="Otmsoal2Collection" element="top:Otmsoal2Collection"/>
    </wsdl:message>
    <wsdl:portType name="CallKC1_ptt">
        <wsdl:operation name="CallKC1Select">
            <wsdl:input message="tns:CallKC1Select_inputParameters"/>
            <wsdl:output message="tns:Otmsoal2Collection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
